### ISSUE TITLE
add link to PR in issues

### ISSUE THREAD

**Issue by danielegallingani** [buildo/github-workflow-pal#107]
finding PRs starting from issues is painful, we do not have a way to see if there is a PR linked to the issue from the issue view.
Currently we only have the `WIP` and `in review` labels in the issue - no link and no joy makes Jack a dull boy

discussed offline with @dhinus and @gabro 

@FrancescoCioria any thoughts?

## requirements
in the issue screen:
- add a "Open PR" button in the right menu to open PRs

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
a **very** clear drawing of the desired output

![image](https://cloud.githubusercontent.com/assets/696969/21988451/931bf6f2-dc07-11e6-9cb4-7b212e7f22ce.png)

**Comment by danielegallingani** [comment]
suggestion from @giogonzo have the link also in the issue list?

**Comment by francescogior** [comment]
Have the link in the issue list is much more difficult from a chrome extension pov.
I start to implement the feature for the issue page following the very clear specs
