### ISSUE TITLE
Add a link to the issue in issue preview

### ISSUE THREAD

**Issue by gabro** [buildo/github-workflow-pal#110]
## requirements
When opening the issue preview, there's no link to the original issue.
Can we have a link (maybe in the title?)?

**Comment by FrancescoCioria** [comment]
@gabro note that you already have a link in the PR.
do we really need this?

**Comment by gabro** [comment]
I think so, because the preview can be long and once it's open the link in the PR is way down the page.

**Comment by francescogior** [comment]
Probably not indispensable but easy enough to implement without discussing further
