### ISSUE TITLE
Ghost comment on pr 

### ISSUE THREAD

**Issue by ascariandrea** [buildo/github-workflow-pal#15]
# how to reproduce
- comment on a pr 

# specs
- No idea for now :/

# misc
after adding a comment on a pr the comment isn't displayed. A refresh cause the comment to appear for a while and suddenly disappear.

**Comment by gabro** [comment]
Sorry, I can't reproduce. Which version of the extension are you using?

**Comment by ascariandrea** [comment]
I have the  0.3.0 :)
-- 
Andrea Ascari
dev @ buildo

ph	3405348124
ma	dev.ascariandrea@gmail.com

gh	github.com/ascariandrea
in	linkedin.com/ascariandrea

pi	02568700351

Sent with Airmail

On 11 gennaio 2016 at 17:25:06, Gabriele Petronella (notifications@github.com) wrote:

Sorry, I can't reproduce. Which version of the extension are you using?

**Comment by gabro** [comment]
Try v0.3.1 or wait for 0.4.0 to be released :)

**Comment by FrancescoCioria** [comment]
@ascariandrea can we close this?

**Comment by ascariandrea** [comment]
Yes, I haven't seen in a while :)
