### ISSUE TITLE
automatize milestone change workflow

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-workflow-pal#19]
## requirements
- our milestone workflow is as follows:
  - issues to focus on stay in `this week`
  - all issues that have to be considered soon stay in `next week`
  - all other issues do not have a milestone assigned
- the milestone switch is a mechanical procedure that executes these steps:
  - move all open issues from `this week` to `next week`
  - rename `this week` to `2016-02-14` (the "due date" of the milestone) and close it
  - rename `next week` to `this week`
  - create a new milestone `next week` with due date set to this week's due date + 7 days

## misc
open milestones:
![image](https://cloud.githubusercontent.com/assets/554092/12577356/1c5e94a8-c41a-11e5-9b01-cfe89bc35d88.png)
closed milestones:
![image](https://cloud.githubusercontent.com/assets/554092/12577353/17790ff4-c41a-11e5-86b0-bf16a8860d16.png)

**Comment by FrancescoCioria** [comment]
the real complexity of this issue should be handled by `github-prettifier`:
We should improve it to listen for other custom requests (not only GitHub webhooks) and delegate to it this task. The chrome extension should only add a button to trigger this action.

**Comment by lucacioria** [comment]
@giogonzo how relevant is this for the current LOL process? it's now you doing the task :p if you don't really care, feel free to close this issue.

**Comment by giogonzo** [comment]
yes, closing for now
