### ISSUE TITLE
Button with link to my issue of current milestone

### ISSUE THREAD

**Issue by francescogior** [buildo/github-workflow-pal#20]
I find myself very often using this keys combinations
- `G + I`
- `A + 'fr..'`
- ` M + 'thi...'`

to get https://github.omnilab.our.buildo.io/buildo/labonline/issues?q=is%3Aopen+is%3Aissue+assignee%3Afrancescogior+milestone%3A%22this+week%22

Bonus would be to have 2-3 buttons with link to the filter per label for 'starred' ones, say, 'WIP', 'IN REVIEW', 'BUG'...

**Comment by lucacioria** [comment]
+1
