### ISSUE TITLE
add warning if CI hasn't completed/passed 

### ISSUE THREAD

**Issue by utaal** [buildo/github-workflow-pal#23]
Migrated from https://github.com/buildo/infra/issues/118, by @FrancescoCioria .

I think we should add another checkbox when the CI build is in progress or if it has failed. The message could be something like:

* "WARNING: the CI build is in progress. Are you sure to continue?"
* "WARNING: the CI build has failed. Are you sure to continue?"

Do you think we're over-engineering it @gabro ? (the checkbox would be visibile only if not safe to merge)

---

classes we may look for to know if build failed:
`.completeness-indicator-error` on indicator label
`.text-error` on `h4.status-heading`

**Comment by lucacioria** [comment]
comments on this? 

Do you guys remember episodes where this functionality would have prevented errors or saved considerable time?

**Comment by gabro** [comment]
GitHub UI is already partially discouraging merging without waiting for the CI to pass (merge button is grey instead of green and less prominent).

I think we can reconsider this if and when we have evidence of "early merges" that caused issues.

**Comment by lucacioria** [comment]
ok, @FrancescoCioria opinions? otherwise closing this for now

**Comment by FrancescoCioria** [comment]
I can't recall any serious episode where we merged an incomplete branch because of this. I say we close it
