### ISSUE TITLE
add "new feature or enhancement" as buildo issue

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-workflow-pal#24]
## requirements
- we need to have a new buildo issue that serves as the generic "new feature or enhancement" issue, which has:
  - mandatory `requirements` section
  - optional `specs` and `misc` sections
  - optional, but suggested, topic in the title

## specs
- add a button in the "new buildo issue" dropdown called "new feature or enhancement" (maybe a shorter but still correct name?)
- remap the `c` shortcut to this actions, overriding the default create issue
- create a template with sections as specified in the requirements above, in the order `requirements`, `specs`, misc
- do not add any label
- prepopulate the title with `[_topic_] _title_` where topic is there to remind/suggest user that it is good to specify a topic in square brackets before the issue title
  - if feasible, make `_topic_` already selected at the beginning so that users can start typing right away

**Comment by francescogior** [comment]
- I would add `new feature` and `enhancement ` as two different issue templates
- Why not labels? I would add `new feature` and `enhancement` labels

**Comment by FrancescoCioria** [comment]
CI: `33:70  error  Infix operators must be spaced  space-infix-ops`

**Comment by francescogior** [comment]
> prepopulate the title with [_topic_] _title_ where topic is there to remind/suggest user that it is good to specify a topic in square brackets before the issue title

isn't this valid in general for the issue templates?

**Comment by FrancescoCioria** [comment]
I don't think so because we're using *topics* only for new macro features never for bugs/defects

PS: have a look at #18

**Comment by lucacioria** [comment]
@francescogior we treat new features and enhancement as the same thing, we did not see any value in separating further

also, no labels are needed because they are the standard, default type of issue

regarding the topic thing, I think it's less useful for defects / bugs as they are not typically nested/macro.. but it's not a rule and I don't have a strong opinion on this one. We can add it and see if/how people use it (not as part of this issue, feel free to open a new one for that)
