### ISSUE TITLE
It should work anywhere in github

### ISSUE THREAD

**Issue by francescogior** [buildo/github-workflow-pal#33]
## description
I think it's not meaningful for this tool to work only on buildo github repos

## specs
remove regex

**Comment by FrancescoCioria** [comment]
> I think it's not meaningful for this tool to work only on buildo github repos

Most of the features are very opinionated and could work only within our workflow...
Take for example the "New buildo issue" button. It completely replaces the default GitHub button and forces you to chose one of our templates. I'm not sure we should force everyone at buildo to use those template for personal projects.

Other features (like the test-plan check, sub-issues button, My Milestone) are almost always useless outside of buildo, but not harmful (you can simply ignore them)

/cc @buildo/everyone

**Comment by gabro** [comment]
I wouldn't want this to work outside buildo repos, but we can easily make this a config option.

**Comment by FrancescoCioria** [comment]
@francescogior with #42 we've added a (rudimental) config interface. If you want this feature you should add a checkbox to the form inside the popup to manually enable it for any github repo.

**Comment by lucacioria** [comment]
not sure of the use case, would it help **buildo** people while browsing other repos? What is the advantage of this?

**Comment by gabro** [comment]
Especially with the advent of official issue templates by github, I wouldn't want this features outside of our organization.

**Comment by francescogior** [comment]
ok fine to me to close this
