### ISSUE TITLE
[UX] visualize current milestone progress

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-workflow-pal#43]
## requirements
- current milestone progress (`this week` milestone) is often overlooked
  - developers have no idea of the progress made
  - and at times work on issues outside of the current milestone without realizing
  - and at times they lose focus on the milestone objectives, while doing something else..
- we need to show in a clear way the progress done on the current milestone, in a simple way
  - we are not going to estimate task size (no story points) but we're only counting a task as 1
  - we should exclude `macro` issues, which can span more than 1 iteration
  - we should visualize the overall milestone progress rather than the personal progress, as our objective is to increase team performance
    - example: I finished my tasks, but the milestone is overall in bad shape, I **should** go and help someone else
    - example: it's ok to have unassigned issues in the milestone, which anyone can grab if they want when they finished their issues. (we can't do this now as they would never be seen and grabbed..)

## specs
- progress bar in the issues page
  - color green for closed, yellow for in review, grey for WIP, transparent for the open ones

## misc
a good and practical read on agile workflow with github:
https://zube.io/blog/agile-project-management-workflow-for-github-issues/

**Comment by FrancescoCioria** [comment]
for reference, have a look at this issue on `core`: https://github.com/buildo/core/issues/201

**Comment by lucacioria** [comment]
closing in favor of https://github.com/buildo/milestone-overview
