### ISSUE TITLE
register on chrome store

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-workflow-pal#44]
## requirements
- must be easy to install and keep updated

## specs
- use google store for extensions

**Comment by lucacioria** [comment]
@FrancescoCioria @francescogior @gabro we have some pressure from Abbott on this, can we schedule this for tomorrow in our R&D friday? Who wants to self-assign this?

**Comment by francescogior** [comment]
I guess you are talking of 'Chrome Store'.

I think I can do this

**Comment by lucacioria** [comment]
thanks, I've updated the issue title

**Comment by francescogior** [comment]
Enjoy https://chrome.google.com/webstore/detail/buildos-github-workflow-e/chkjadbenkogbdkdjeckjfbbnjpmbelm
