### ISSUE TITLE
[productivity/code review] Issue/PR split view

### ISSUE THREAD

**Issue by francescogior** [buildo/github-workflow-pal#45]
## requirements

We at Buildo rely a lot on the dichotomy Issue/PR to handle the workflow.

I think Github lacks an adequate UX to display it.

I was wondering if we can build a tool (in the chrome-extension or as another project) to get something like this

![](https://i.gyazo.com/8410a51e07fef31a72d1ee662edd2d13.gif)

**Comment by lucacioria** [comment]
seems interesting, however I'd like to know exactly:
1. what are the objectives?
2. how many errors do you think it'll prevent? do you have examples?

**Comment by gabro** [comment]
Still relevant or can we close this?

**Comment by francescogior** [comment]
Closing :(
