### ISSUE TITLE
Add generic issue without template

### ISSUE THREAD

**Issue by gabro** [buildo/github-workflow-pal#46]
## requirements
The extension removes the default `New Issue` button, but in some instances it's useful to work without a template (or to use the github's ISSUE_TEMPLATE feature, e..g in buildo/core).

I propose we add an other issue type that simply mimics the `new issue` button we removed.

**Comment by francescogior** [comment]
@gabro what do you mean with 'add another button that mimics the `new issue` button we removed'?

Isn't much easier and sensed to unhide it? Like in the screenshot below

![image](https://cloud.githubusercontent.com/assets/3280300/14389020/f4ac2f30-fdb0-11e5-8ee7-5cb4276f5561.png)

**Comment by gabro** [comment]
As discussed offline, this would change the visual priority more than indented.
We still want to discourage an issue to be opened without a template.
