### ISSUE TITLE
make it easier to distinguish template placeholders from actual content

### ISSUE THREAD

**Issue by gabro** [buildo/github-workflow-pal#59]
## requirements

Template placeholders are useful, but it's difficult to tell actual content apart from a template placeholder.

Basically I'm proposing this:

| before | after |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/691940/15176582/13c048a0-176c-11e6-830d-48fbff63543e.png) | ![image](https://cloud.githubusercontent.com/assets/691940/15176561/f8abdc14-176b-11e6-8f26-302bc4f79cc0.png) |
## specs
- use `quotes` to highlight placeholder paragraphs
- edit regex for autoselect

**Comment by gabro** [comment]
@lucacioria @FrancescoCioria @francescogior @ascariandrea @giogonzo thoughts?

**Comment by francescogior** [comment]
❤️

**Comment by giogonzo** [comment]
nice!

**Comment by ascariandrea** [comment]
I was thinking about to convert them to comments, but this is a better solution, good 😎

**Comment by FrancescoCioria** [comment]
I like it, but this should be tested carefully as `{ ... }` is used for other purposes too: what happens if I write
```
`{ ciao: 'ciao' }`
```
???

If it turns out to have conflicts we could put `>` before any placeholder and rely on github default style

**Comment by francescogior** [comment]
As far as I know, there's no way to select those placeholder via CSS

It seems more viable the solution proposed by @ascariandrea, replacing brackets with html comments to delimitate placeholders

**Comment by francescogior** [comment]
Investigated a little

- although one can write some HTML inside GH comments form, all the attributes will be stripped out, thus it's not possible to add inline style nor class names.
- one exception is the `id` attribute, it will hold in the output and its value would be just prefixed with `user-content-`
- there are actually some allowed tag and attributes (https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L44-L106)

#### Example:
<div class='this-would-be-easier' style='color: rebeccapurple' id='this-works'>ciaone!</div>
![image](https://cloud.githubusercontent.com/assets/3280300/15254927/7b9fd69c-1939-11e6-8f5b-fb9544d7f5e7.png)

![image](https://cloud.githubusercontent.com/assets/3280300/15254917/74b120fc-1939-11e6-811c-b93e71905f95.png)

So, the matter would be to:
- define a funny id name, such `funnyName`
- PR here with one line of CSS ` #user-content-funnyName { opacity: .5 }
- PR in nemobot and update templates nesting all the `{...}` inside divs

`<div id='funnyName'>{placeholder}</div>`

**Comment by FrancescoCioria** [comment]
Cool!

**Comment by gabro** [comment]
sounds very reasonable

**Comment by francescogior** [comment]
Serious?

I thinks it would be bad to have html around the placeholders, they would make the textarea very dirty in editing mode, I think @ascariandrea's idea to use html inline comments (thus no CSS, no dirty textarea, no opacity but just invisible placeholder in preview mode) is much more viable

**Comment by francescogior** [comment]
Somehow was decided to use

> quotes

So no CSS involved since it relies on Markdown formatting.

Working for supporting autoselect of quotes paragraph, (updated specs)
