### ISSUE TITLE
in the comment box, use a fixed-width font

### ISSUE THREAD

**Issue by francescogior** [buildo/github-workflow-pal#61]
## requirements
![image](https://cloud.githubusercontent.com/assets/3280300/15321076/89343af2-1c34-11e6-9130-bd78aa0144d8.png)

a plus would be a dark theme

![image](https://cloud.githubusercontent.com/assets/3280300/15321105/b0e06792-1c34-11e6-9f1c-e67f8afeedf3.png)

a plus plus would be a configurable theme
## specs
add `.comment-form-textarea: { font-family: monospace; }`

**Comment by lucacioria** [comment]
@francescogior @gabro is this issue relevant? are people really interested in this? If no quorum/decision on feature requests is made after a few months I thing issues should be closed :)

**Comment by francescogior** [comment]
I'd like to have it but I'm the only one maybe. Sure, it may be configurable / hidden for who doesn't want it

**Comment by gabro** [comment]
I don't see this as related to buildo's workflow and it would be extra code (not much, but still) to maintain.

You can always build your own style using something like https://chrome.google.com/webstore/detail/styler/bogdgcfoocbajfkjjolkmcdcnnellpkb?hl=en

**Comment by francescogior** [comment]
Ok you won I like styler

**Comment by gabro** [comment]
💅
