### ISSUE TITLE
Remove Gyazo

### ISSUE THREAD

**Issue by gabro** [buildo/github-workflow-pal#65]
## description

seriously

**Comment by lucacioria** [comment]
Is this planned / agreed upon? I have created a milestone `focus` to put a few selected issues to focus on, if this is relevant you can put it there

**Comment by francescogior** [comment]
My specs proposal:

FROM
![image](https://cloud.githubusercontent.com/assets/3280300/17744405/d5440cae-64a7-11e6-93e8-cba01a1b5fa7.png)

TO
![image](https://cloud.githubusercontent.com/assets/3280300/17744462/077a7dfc-64a8-11e6-8f1d-cc4933efe800.png)

**Comment by gabro** [comment]
Is anyone using this?

**Comment by francescogior** [comment]
yes

![](https://i.gyazo.com/39151dfab376094ae40a379b1a90ed05.gif)

**Comment by gabro** [comment]
Is anyone **that is not you** using this?

**Comment by francescogior** [comment]
I'm still using it, anyone @buildo/everyone who really hates it? (Just to be informed, I'm not going to remove it, not today, maybe)

**Comment by gabro** [comment]
I'm fine with keeping it. Enjoy :P
