### ISSUE TITLE
make sub-issue button more visible

### ISSUE THREAD

**Issue by dhinus** [buildo/github-workflow-pal#66]
## description

I struggled to find the sub-issue button, as I was expecting to find it as part of the "new buildo issue" dropdown.
## how to reproduce
- look intensely at an issue page
- open the "new buildo issue" dropdown and check if there is a "new sub-issue" option
- feel stupid
- wonder if the sub-issue is only available on specific conditions
- check [this gif](https://buildo.gitbooks.io/book/content/workflow/6.workflow-pal.html)
- ah-ha!
## specs

Discussed with @gabro - moving the "sub-issue" inside the dropdown would make it less convenient. Maybe we can just reposition it?
## misc

![new-sub-issue](https://cloud.githubusercontent.com/assets/474311/15897453/cc95e84c-2d94-11e6-990c-64dec1cf3940.png)

**Comment by gabro** [comment]
Agreed with the problem. I don't like the proposed positioning though (esthetically :P)

Any other opinions? @buildo/everyone

**Comment by danielegallingani** [comment]
![screen shot 2016-06-08 at 4 31 03 pm](https://cloud.githubusercontent.com/assets/696969/15897868/6b1f5d76-2d96-11e6-8097-9370e5e3ef63.png)

what about this one?

**Comment by gabro** [comment]
Better. This?

![image](https://cloud.githubusercontent.com/assets/691940/15897940/afadf9ca-2d96-11e6-9c3c-3ca0554e8eb9.png)

**Comment by danielegallingani** [comment]
like it, I'd recommend a `1px dotted green` border around the button though
:P

**Comment by francescogior** [comment]
or this
![image](https://cloud.githubusercontent.com/assets/3280300/15898033/f96c273a-2d96-11e6-8354-6475549acc40.png)

but I think it wouldn't be *that* bad to have it in the dropdown actually

**Comment by gabro** [comment]
Minor pro of having it in the sidebad: when you scroll, it sticks to the right.

So if you have a long issue and you scroll down to the **sub-issues** section, you still have the "Add Subissue" button available on the right.

![image](https://cloud.githubusercontent.com/assets/691940/15898170/6cce3bdc-2d97-11e6-8e59-e229dc090a77.png)

**Comment by francescogior** [comment]
:+1:

On Wed, Jun 8, 2016 at 4:39 PM Gabriele Petronella <notifications@github.com>
wrote:

> Minor pro of having it in the sidebad: when you scroll, it sticks to the
> right.
>
> So if you have a long issue and you scroll down to the *sub-issues*
> section, you still have the "Add Subissue" button available on the right.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/691940/15898170/6cce3bdc-2d97-11e6-8e59-e229dc090a77.png>
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/buildo/github-workflow-pal/issues/66#issuecomment-224610375>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADINrFJGFDPSRo62A5nWxJr28QoQOTc6ks5qJtQRgaJpZM4IxAxG>
> .
>
-- 
Francesco Giordano ~ buildo

**Comment by ascariandrea** [comment]
Agree to have it on the top of the right sidebar!
