### ISSUE TITLE
enforce topic on macro and sub issues

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-workflow-pal#67]
## requirements
the topic is what is written in square brakets at the beginning of an issue title: `[sample view] implement buttons`

- per new guidelines, the topic should be written if, and only if, the issue is a macro or sub issue
  - find a way to discourage opening sub-issues without a topic set
  - do not encourage a topic on standard issues that don't contain sub-issues

## specs
- disable the "new sub-issue" button if there is no topic in the issue title
  - explain the reason with a popover or other message
- do not put the topic in the default template
  - otherwise we'd continue writing it everywhere..

## misc
{optional: other useful info}

**Comment by lucacioria** [comment]
@gabro @FrancescoCioria @francescogior @giogonzo we talked about this last week, check the issue and tell me if this implementation is good in your opinion :)

**Comment by francescogior** [comment]
what about, when one clicks in the `add subIssue` button a modal/text input is prompt and the user must write the topic if not present?

**Comment by lucacioria** [comment]
well that's even better!

**Comment by FrancescoCioria** [comment]
> what about, when one clicks in the add subIssue button a modal/text input is prompt and the user must write the topic if not present?

IMO this is very complex and leads to the same result than a simple tooltip
