### ISSUE TITLE
Add `My PRs` button in pr section

### ISSUE THREAD

**Issue by ascariandrea** [buildo/github-workflow-pal#69]
## requirements
- add button that link to pr list filtered by `involves:$username`
  - maybe the filter `milestone:this-week` can be added
## specs
- same logic as `My Milestone` button
## misc

{optional: other useful info}

@buildo/everyone ?

**Comment by gabro** [comment]
I don't personally have this need, but I'm not against having this filter.

The only thing: I would put it in the filter list (simply adding an element), e.g. here:

![image](https://cloud.githubusercontent.com/assets/691940/15923304/cf0e8168-2e2c-11e6-9b13-8a6171ecc8a9.png)

**Comment by ascariandrea** [comment]
I don't have strong opinions about button placement, I mentioned the `My Milestone` button for association.
I haven't personally ever opened that dropdown in my life, so adding an option could be the reason to start to use it :)

**Comment by gabro** [comment]
Yup. Since I think most people won't use it, I thought it would be a good solution for avoid cluttering the interface with unused buttons.

**Comment by FrancescoCioria** [comment]
long term option: make things configurable by project/user

**Comment by ascariandrea** [comment]
Everyone agrees or at least isn't contrary to add it as additional option of filter dropdown?

**Comment by gabro** [comment]
👍  💯

**Comment by francescogior** [comment]
This is a little bit old. Is still needed? By the way, `My milestone` button is by now useless :(

**Comment by lucacioria** [comment]
what does the button do exactly? alwyas opens `this week` with filter myself? IMO it's useless now.. github proved to be a good tool for execution, but a very bad tool for planning. I have no intention on going back to the way things were before :p 

github don't be offended!  you will always be the best for code and pull requests..

**Comment by francescogior** [comment]
Ok! closing...
