### ISSUE TITLE
add UI to split macro issues

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-workflow-pal#91]
## requirements

be able to split a macro issue in 2: open issues and closed issues
## misc

refer to documentation in nemobot repo here https://github.com/buildo/nemobot

**Comment by francescogior** [comment]
@lucacioria is this still relephant?

**Comment by lucacioria** [comment]
not really, the idea is that issues are much more **short lived** now so it doesn't really matter, you can always close and reopen at a later date from trello
